import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import TransitionPrivider from "@/components/TransitionPrivider";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Roman",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
      <TransitionPrivider>
        {children}
      </TransitionPrivider>
      </body>
    </html>
  );
}
